# Generated by Django 4.1.5 on 2023-01-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderform',
            name='date',
        ),
        migrations.RemoveField(
            model_name='orderform',
            name='email',
        ),
        migrations.RemoveField(
            model_name='orderform',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='orderform',
            name='text',
        ),
        migrations.AddField(
            model_name='orderform',
            name='order_forms',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
