# Generated by Django 4.1.5 on 2023-01-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0002_remove_orderform_date_remove_orderform_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('form_data', models.JSONField(default=dict)),
            ],
        ),
        migrations.DeleteModel(
            name='OrderForm',
        ),
    ]
